#ifndef COMMUNICATIONLIBRARY_GLOBAL_H
#define COMMUNICATIONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMUNICATIONLIBRARY_LIBRARY)
#  define COMMUNICATIONLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMUNICATIONLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMUNICATIONLIBRARY_GLOBAL_H
